name: AutoPix
version: 1.0.24
main: io.github.warleysr.autopix.AutoPix
author: warleysr
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  autopix:
    description: Valida uma transacao realizada por PIX
    aliases: [ap, pix]
  autopixmenu:
    description: Abre o menu de itens disponivel para compra por PIX
    aliases: [comprarpix]